# Stage 1: Build the app with JDK 17
FROM maven:3.9.9-amazoncorretto-17-debian AS build

WORKDIR /app

COPY ./server/OrderCoffeeBE/pom.xml .

RUN mvn dependency:go-offline -B

COPY ./server/OrderCoffeeBE/src ./src

RUN mvn package -DskipTests

# Stage 2: Run the app with JDK 17
FROM openjdk:17-jdk

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]